name: Security & Deployment

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        
    - name: Install PHP Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: PHP Security Check
      run: composer audit
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run Security Checks
      run: make security-check

  deploy-staging:
    needs: security-scan
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 755 storage bootstrap/cache
      
    - name: Create Docker Image
      run: make docker-build
        
    # Add your deployment steps here
    # This is a placeholder for your actual deployment process
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging environment"
        # Example: Add your deployment script or commands here
        # ssh user@server 'cd /path/to/project && git pull && composer install && php artisan migrate --force'
