name: Security & Deployment

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        
    - name: Install PHP Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: PHP Security Check
      run: composer audit
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run Security Checks
      run: make security-check

