name: Sync Wiki

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Wiki Bot"
          git config --global user.email "actions@github.com"

      - name: Push Wiki Changes
        run: |
          # Clone the wiki repository
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          
          # Ensure wiki directory exists
          mkdir -p wiki
          
          # Copy docs content to wiki directory
          cp -r docs/* wiki/
          
          # If README.md exists, rename it to Home.md for wiki landing page
          if [ -f wiki/README.md ]; then
            mv wiki/README.md wiki/Home.md
          fi
          
          # Push changes
          cd wiki
          git config user.name "GitHub Wiki Bot"
          git config user.email "actions@github.com"
          git add .
          
          # Only commit if there are changes
          if git status --porcelain | grep .; then
            git commit -m "Update wiki from docs directory"
            git remote set-url origin https://x-access-token:${{ secrets.WIKI_TOKEN }}@github.com/${{ github.repository }}.wiki.git
            git push
          else
            echo "No changes to commit"
          fi
