name: Sync Wiki

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki-sync.yml'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Sync wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          token: ${{ secrets.WIKI_TOKEN }}
          path: docs
