name: Sync Wiki

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Sync wiki
        uses: joeizzard/action-wiki-sync@master
        with:
          wiki_folder: wiki
          username: GitHub-Wiki-Bot
          email: wiki@github.com
          commit_message: "Update wiki content"
          commit_username: ${{ github.actor }}
        env:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
